### ISSUE TITLE
KNMI app device not shown in devices list for display confuguration

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#10]
In button/display configurator. Should all devices be shown in the device drop down?

It looks I cannot find this one:
![Schermafbeelding 2023-09-25 om 21 04 28](https://github.com/AdyRock/com.ady.button_plus/assets/123867346/fc9d734c-9cc7-4db0-94c2-1cdc3106d3bf)
Could it be because this device doesn’t have capabilities that can be changed? Only (weather) info. For button configuration I understand this is not useful, but for display I really would like to display temperature, wind direction and weather forecast for instance…

**Comment by AdyRock** [comment]
Fixed
