### ISSUE TITLE
MQTT topic for button clicks not a child in homey/btn_XXXXX topic

### ISSUE THREAD

**Issue by oh2th** [AdyRock/com.ady.button_plus#103]
The button press events for longpress, clickrelease and click are not childs of the btn_XXXXX topic:

<img width="196" alt="Screenshot 2024-03-04 at 16 36 59" src="https://github.com/AdyRock/com.ady.button_plus/assets/59442255/0894e0b4-66de-4ef4-a345-2507661661c4">

this could result on not catching button clicks from multiple devices.

**Comment by AdyRock** [comment]
The Button ID is part of the payload that is posted with the message, so it doesn't need to be a child.
All the topics with btn_XXXXX are message from Homey to the Button. The click, longpress and clickrelease are messages from the Button to Homey.

**Comment by oh2th** [comment]
Agree
