### ISSUE TITLE
No Homey data shown on Button Plus, button presses not registered in Homey

### ISSUE THREAD

**Issue by leeuweriq** [AdyRock/com.ady.button_plus#104]
**Homey**
- Model: 2023
- Homey Firmware Version: 10.3.1
- App Version: 0.3.17
- Button+ Firmware Version: 1.11

**Bug**
Unable to establish communication between Homey and Button Plus. Unable to display any data on the Button Plus or getting button presses registered in the Homey Pro. I've tried hard resetting the BP, uninstalling and adding the BP app on the Homey Pro and creating new display and button configurations through the Homey app on iOS. 

I am able to add new display configurations (for example a "Temperature" block in the top left corner of the screen). I am also able to browse the Homey broker topics to select a temperature topic for one of the connected zigbee temperature sensors (which broadcasts the correct temperature to the Homey because I am able to see the temperature in the Homey app itself). But after saving the configuration the value in the Temperature block on the BP remains empty.

When checking the diagnostics logs in the ButtonPlus Homey app, I'm seeing these log entries:
```
undefined 
2024-03-11T15:25:01.775Z Invalid connector type: 0 on 0 
2024-03-11T15:25:01.782Z Error: Invalid connector type: 0 on 0 
2024-03-11T15:25:01.814Z Invalid button bar configuration: null 
2024-03-11T15:25:01.817Z Error: Invalid button bar configuration: null
```

Any idea what I'm doing wrong?

**Comment by AdyRock** [comment]
What do you see in the web interface of the Button plus?

**Comment by leeuweriq** [comment]
I'm guessing you're refering to the GUI where you see the display and button layout? It shows exactly the same as on the BP itself. So a block with a title "Temperature", with an empty value. Weird thing is that in the web interface under "MQTT Brokers" I only see the 'buttonplus' broker, but not the Homey:

<img width="1378" alt="image" src="https://github.com/AdyRock/com.ady.button_plus/assets/6400302/9b8cc846-994d-4fb6-b402-7fa62548e466">

**Comment by leeuweriq** [comment]
I've manually added the Homey broker configuration through the BP web interface and that has done the trick. After going back to the Button + Homey app, and selecting Broker Configuration, the Homey broker wasn't there so I've added it there too. Aren't these two systems 'linked' somehow? Thanks!

**Comment by AdyRock** [comment]
I'm not sure why the Homey broker wasn't in Homey as it should be created automatically and presented from being deleted. Did you start with a very early version of the app?
The synchronisation is one way, from Homey to Button +.

**Comment by leeuweriq** [comment]
No it is the most recent version. I've got it working now and sort of figured out how the two interfaces (BP app for Homey and the BP web interface) work. Thanks for your quick response!
