### ISSUE TITLE
no access to the button config. use homey app

### ISSUE THREAD

**Issue by DJSissi** [AdyRock/com.ady.button_plus#107]
*

**Comment by AdyRock** [comment]
Sorry,  I didn't understand your steps with the '...'.
From your last post, does that mean it is working now?

**Comment by DJSissi** [comment]
Sorry for the confusion.
After I tried it to configure it from the Phone App it works, but only for the Display und the first row of buttons.
The other two rows of button are not reaction on the config. over the App.

If I try to chance button over the Button+ web interface this is working still but will be overwritten from the App.

Thx,
Josef


Am 27.05.2024 um 10:48 schrieb Adrian Rockall ***@***.***>:


Sorry, I didn't understand your steps with the '...'.
From your last post, does that mean it is working now?

**Comment by DJSissi** [comment]
I didn't know that i had to make an assignment in the device, I tried it now and it worked. thx!
