### ISSUE TITLE
Since firmware v1.13 Button+ it is possible to display letters in font size 5

### ISSUE THREAD

**Issue by mythosagoras** [AdyRock/com.ady.button_plus#110]
Since firmware v1.13 Button+ it is possible to display letters in font size 5. 
Can this also be made available in the Homey Button+ App? 
That would be fantastic.

![fontsize buttonplus](https://github.com/user-attachments/assets/ff9999ad-dc46-42af-b313-bfb0e86b133f)

**Comment by AdyRock** [comment]
New test version in the store now supports font size 5.
Thanks for the heads up on that one.

**Comment by mythosagoras** [comment]
I appreciate your quick response and update 👌

Op di 20 aug 2024 23:13 schreef Adrian Rockall ***@***.***>:
