### ISSUE TITLE
Device (and capability) drop-down menu's are empty in button configuration

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#12]
Somehow the drop down menu's for device and capabilities are empty as of version 0.03

**Comment by AdyRock** [comment]
Hmm, I'm not seeing this issue.
![image](https://github.com/AdyRock/com.ady.button_plus/assets/38184396/8ac0126c-a669-45b6-aeaa-1fb325c52316)
![image](https://github.com/AdyRock/com.ady.button_plus/assets/38184396/804b26fe-94b3-405f-ae86-4fb1e8ebea7d)

Could you provide any more information to recreate the problem?

**Comment by Torch1969** [comment]
Install have empty dropdown’s
Diagnostic report 26d222ca-11da-4e83-b3da-7a8a52a5e316
![Schermafbeelding 2023-10-15 om 18 52 02](https://github.com/AdyRock/com.ady.button_plus/assets/123867346/113b4908-f6eb-4501-90b5-07d8da5800ab)

**Comment by Torch1969** [comment]
After restart of app, everything works fine 🤔

**Comment by AdyRock** [comment]
Strange. The log didn't show anything unusual apart from a device not found error, but that seems to have been for a MQTT message.

**Comment by AdyRock** [comment]
Shall I close this off now, or have you still noticed the issue?

**Comment by Torch1969** [comment]
Yep, for as far as I remember it was solved after restart of the app. When/if it shows up again, we can file a new bug.

**Comment by Torch1969** [comment]
And closed
