### ISSUE TITLE
Add possibility to change button label with Homey action card

### ISSUE THREAD

**Issue by GithubBram** [AdyRock/com.ady.button_plus#52]
To change a button label, the button bar needs to have a different configuration.
But there is a limited nr of button bar configurations.
When there is an action card to change a button label, the label can be changed independent of the configuration.
The use-case is for example a button assigned to a Homey virtual button, and the action of that button can be different depending on condition cards in the flow (e.g. before or after noon).

**Comment by AdyRock** [comment]
Will be available in version 0.2.3
