### ISSUE TITLE
geen inlog gegevens homey pro 2023

### ISSUE THREAD

**Issue by demuy** [AdyRock/com.ady.button_plus#53]
**Homey**
- Model: 2023
- Firmware Version: 10.1.4
- App Version: v0.2.2

**Describe the bug**
geen inlog voor button+ bij eerste toevoegen device

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by AdyRock** [comment]
If you are referring to the simulator, I have removed that now as the app uses some new features that are not available in the simulator.
For local displays, they are discovered using mDNS and don't require a login,

**Comment by AdyRock** [comment]
I am closing the issue as I think it is answered, but if you have any further comments then feel free to open it again.
