### ISSUE TITLE
button + app laat display en knoppen vastlopen

### ISSUE THREAD

**Issue by demuy** [AdyRock/com.ady.button_plus#58]
**Homey**
- Model: 2023
- Firmware Version: 10.1.4
- App Version: v0.2.2

versie Button + : 1.03
![IMG_2047](https://github.com/AdyRock/com.ady.button_plus/assets/55797597/f484b7d9-9108-4beb-b657-a135139eb9e8)

**Describe the bug**
tekst niet goed bij bar , rechter kant van knoppen werkt niet zowel bij display als bar

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by AdyRock** [comment]
I have published a new version of the app but I'm not sure it will fix those problems.
If you open a web browser and set the URL to http://10.0.1.53 do you see what is expected there?
If you click on the button text, do you see the options toggle?

**Comment by demuy** [comment]
Hoi Andy Rock,Ik zie als ik op de website op de knoppen druk idd de  schakelaar meegaan , maar rechts niet.Ik heb vanochtend met de nieuwe versie gezien dat het nog niet weg was maar heb de app wel opnieuw opgestart maar niet eerst verwijderd . Vannavond na het werk ga ik ermee verder .Dank voor de terugkoppeling .Met vriendelijke groet raimond  Bonlite zonweringenKennemerlaan 391972 EG. IJMUIDEN Tel.nr 0255-531324E-mail: ***@***.*** 14 dec 2023 om 01:42 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
I have published a new version of the app but I'm not sure it will fix those problems.
If you open a web browser and set the URL to http://10.0.1.53 do you see what is expected there?
If you click on the button text, do you see the options toggle?

**Comment by AdyRock** [comment]
I have published a new version that should fix the right side button issues.
