### ISSUE TITLE
Add possibility to calculate/edit the value to be shown

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#6]
Is it possible to add the possibility to "compose"/edit the value to be shown on the device?

For instance for numeric value based on one or several capabilities and using something like math.js or better logic library.

Or for text strings composed of fixed text and text variables?

**Comment by AdyRock** [comment]
This sounds like it would be suited to using flows to do the calculations, etc and sending the value to the display?

**Comment by Torch1969** [comment]
Yes, that would be a possibility. That way all this functionality doesn't have to be part of this app.

**Comment by AdyRock** [comment]
Issue #7 is now implemented and covers this, so closing this one off.
