### ISSUE TITLE
Reduce API calls on configuration page

### ISSUE THREAD

**Issue by vincent8balls** [AdyRock/com.ady.button_plus#64]
Currently the app is doing multiple requests to the Devices endpoint of Homey. This makes the settings page slower.

This can be reduced to a single function, and filter out the capabilities instead. For example:

```
        function getDevices(devices, type) {
            if(type == 'button') {
                devices.filter(device => device.capabilities.includes('on_off') || device.capabilities.includes('dim'));
            }

            return devices;
        }
```

**Comment by AdyRock** [comment]
Your pull requests have been incorporated in the latest test version.
