### ISSUE TITLE
Add Copy and Paste

### ISSUE THREAD

**Issue by AdyRock** [AdyRock/com.ady.button_plus#66]
Add an option to copy and paste configurations.
If the clipboard format is in JSON then it could be used for sharing, although devices probably won't match

Assignees: AdyRock
Labels: 
Milestone:

**Comment by Torch1969** [comment]
Good idea.
Alternative for own use could be to add a "copy" button of top of configuration page and when pressed, present a drop down with the configurations to choose from.
