### ISSUE TITLE
Add layout configurations

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#67]
A "layout" is a combination of 0-1 display configuration and 1-3 button configurations. 
In a layout configuration page you can choose which/if display configuration should be used on connector 0 and which button configurations should be used on connector 0/1-3.

Then add flow cards to switch to another configuration number. If a layout is activated this way, the corresonding display and button configurations are activated on the defined connectors. This way it is possible to easy switch from one layout to another (for instance using de display buttons, left&right, for scrolling through the layouts).

Maybe also a trigger card for an activated layout configuration.

I think 10-20 layout's should be enough.

**Comment by AdyRock** [comment]
At the moment it's possible to switch configurations on both the display and buttons via Flow cards. I have used those to switch the configuration via the display buttons.

**Comment by Torch1969** [comment]
Yes, I agree it can be done that way already, a pre defined layout configuration would make it a bit more straightforward, but it’s an extra layer of configuration.

**Comment by AdyRock** [comment]
So, I have been thinking about this now that the core of the app is settling down. These are my initial thoughts:

**Comment by AdyRock** [comment]
The [Array of Menus] might need to be a pre-defined size like the other configurations, especially if they are selected via a device capability.

**Comment by Torch1969** [comment]
Nice, you’re adding an extra layer of functionality above the “layout”-configuration (= menu item in your description) I was thinking about. I don’t think you’re missing anything.

Beware, on tweakers.net site Ronald explained that he didn’t have this sort of functionality in mind when designed the button+. See link https://gathering.tweakers.net/forum/list_message/77886540#77886540, (maybe you can translate this to English). He also say’s he’s going to dive into “page support” as he calls it. Maybe you should check your ideas with Ronald and wait for what he’s adding (or not).

**Comment by AdyRock** [comment]
OK, thanks for the heads-up. I will ask Ronald, but I guess it might take some time for him to do that. However I might be able to add it now in such a way that it will be easier to transfer to his plane later.

What are your thoughts about the activating section (Advanced setting or capability)?

**Comment by Torch1969** [comment]
I don’t know what you mean exactly bij “activating”. To be able to switch between the menu’s with the display button’s it’s necessary that it’s a capability right? Also for checking which menu is active?
In which situations would an advanced setting be usefull?

**Comment by AdyRock** [comment]
It doesn't have to be a capability but that is one way. I was just thinking the screen of lists is getting rather full with display and button configurations.

If it's in the advanced options it could just be a numeric field to select the desired menu and enable it for the device.

**Comment by Torch1969** [comment]
Well I guess the user will choose either menu functionality or current (free format) functionality and no one is going to mix them up. So yes, it could be an advanced setting in device settings. As long as the menu can be changed with flow/buttons. The menu item number in advanced settings is the default menu when (re)starting the device?

**Comment by AdyRock** [comment]
The option is to select a menu set. The idea is to be able to configure multiple menu sets so that you can have multiple displays and have different menus on each. 

At the moment also working on a system with Ronald so the switching is done on board.

**Comment by Torch1969** [comment]
Ok, great, sounds good. Advanced setting option looks like good solution. Good to hear you’re developing this with Ronald.

**Comment by AdyRock** [comment]
I'm closing this as the Page option now makes this redundant.
