### ISSUE TITLE
Configure date & time format

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#68]
I would like to be able to change date&time format. Maybe this is available somewhere in homey configuration?

(my personal preference would be dd mmm eeyy (01 jan 2024)) & hh:mm in 24h format (16:40))

**Comment by AdyRock** [comment]
I format the date and time in the app, so will look into adding a setting to select the format.

**Comment by Torch1969** [comment]
Nice thank you.
Maybe in future also a translation for the month names? 😁

**Comment by AdyRock** [comment]
When I tested by setting the language /region code it was giving the correct text. 
I tried with nl, de and fr.
I get the code from Homey's i8n library that it uses for selecting the locale translation. I will log that value in the next update so we can check it is correct.

**Comment by Torch1969** [comment]
I can confirm it works correct with the language setting. Missed this language setting apparently
 when setting date format.

**Comment by AdyRock** [comment]
The language setting is new, so you probably didn't miss it. 
It should have initialised from the i8n part of Homey as that should be set by Homey based on the region.
