### ISSUE TITLE
add button trigger cards for display/button configurations

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#69]
Is it possible to add trigger cards for button events on display configuration and button configuration?

Now the triggers cards are connected to the connectors, but which button configuration is active on a connector can change.

It can be solved now in flows with combination of button event on connector # and a logic card checking for the button configuration number(s) and then de desired action cards for each combination.

Would be nice if this check can be combined.

"The <left/right> button on <display configuration#/button configuration #> is <pressed/on/off/released....>"

**Comment by AdyRock** [comment]
That sounds like a good idea. I am just wondering if the display / button and configuration number will need to be split to give:
"The <left/right> button on <display/button> <configuration #> is <pressed/on/off/released....>", but hopefully that still meets your requirements?
