### ISSUE TITLE
Empty display label gets reset when adding new item

### ISSUE THREAD

**Issue by Joolee** [AdyRock/com.ady.button_plus#73]
**Homey**
- Model: Early 2016
- Firmware Version: 10.0.4
- App Version: 0.2.13

**Describe the bug**
When adding a new item in the 'Display configurations' page, any item with an empty label field gets it's label filled with the capability name.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to app settings > Display Configuration
2. Add a display item with a Homey device and capability
3. Make the 'Label' field empty and save
4. Refresh or do anything you want, label stays empty
5. Add a new display item
6. See the label of the first display item filled in with the capability name

**Expected behaviour**
Label should stay as-is, it works through refreshes and seems to be the correct behaviour

**Additional context**
Using the settings page on Firefox in https://tools.developer.homey.app/tools/app-settings

**Workaround**
Using a space as the label, the Javascript doesn't use 'trim' but somewhere in the communication to the Button+, the space does get trimmed :)

**Comment by AdyRock** [comment]
Hmm, I couldn't think of a reason to have a blank label, so the auto fill of an empty field was supposed to be a convenience. 
I will rethink that.

**Comment by Joolee** [comment]
The default (non-homey) configuration of the Button+ has a temperature display item without a label so I thought it would be an expected and supported feature.

Speaking of no-label, the webinterface of the button also has a small display problem when not using a label:
![image](https://github.com/AdyRock/com.ady.button_plus/assets/570302/fdf9e478-7f04-4cfa-a691-0b3163c84e99)
The display itself shows them properly lined up.

**Comment by AdyRock** [comment]
The web interface is Roberts domain. 
I will do something about the label issue.

**Comment by Torch1969** [comment]
> Hmm, I couldn't think of a reason to have a blank label, so the auto fill of an empty field was supposed to be a convenience. I will rethink that.

Could be handy with text capabilities where text is self explaining, for instance weather forecast. But only if the field takes up less space on the screen when label is empty, which isn’t the case I suppose. Could be a nice feature for Ronald to implement on the device…..😀
