### ISSUE TITLE
Use boolean variable as button

### ISSUE THREAD

**Issue by Joolee** [AdyRock/com.ady.button_plus#74]
**Is your feature request related to a problem? Please describe.**
On/Off buttons are perfectly mappable to On/Off variables, same as On/Off capabilities.

**Describe the solution you'd like**
Add the user-defined On/Off Homey variables to the drop-down list in the button-configuration page.
State of the variable/button should be kept up-to-date both with changes made by Homey and by pushing the device button

**Describe alternatives you've considered**
Create flows to create this capability

**Comment by AdyRock** [comment]
Sounds good.

**Comment by Torch1969** [comment]
+1

**Comment by AdyRock** [comment]
Looks like this one won't be possible as it seems an app doesn't have permission to change variable states.
I can add them as status indicators so the text can change and the lights can come on, but the change of state would have to be done in a flow.

**Comment by AdyRock** [comment]
Added as read-only state, so it shows the value on the button and controls the LED, but a flow is needed to toggle the variable.
