### ISSUE TITLE
Re-Initialize factory-reset Button+

### ISSUE THREAD

**Issue by Joolee** [AdyRock/com.ady.button_plus#76]
**Is your feature request related to a problem? Please describe.**
I performed a factory-reset to make the screenshot for #73. Now I need to remove the device from Homey and add it again. This loses the advanced settings like date-format and all flowcards break.

**Describe the solution you'd like**
Add a 'maintanance' button to the advanced settings to run the Homey setup-process on the Button+ again
and/or
Add a message+button to the Homey Button+ app settings page

**Describe alternatives you've considered**
Elbow grease :)

**Comment by AdyRock** [comment]
Deleting a device from Homey will do that. However, factory resetting the Button + should just allow the connection to be restored. The app uses the device id, which is the last part of the MAC address, as the unique identity.
The only thing you should need to do is reset the IP address on the Homey device if the Button + was given a different one.

**Comment by Joolee** [comment]
IP address was the same but the button and display configurations didn't sync, not even when saving.

I'm thinking this might perhaps have been cause by there not actually being a change to sync because Homey doesn't know the device state was reset. I'll try again later and check what happens when I actually make a change to the config.
