### ISSUE TITLE
top device options missing

### ISSUE THREAD

**Issue by ferdw** [AdyRock/com.ady.button_plus#78]
**Homey**
- Model: 2023
- Firmware Version: 1.0.7
- App Version: 2.16

**Describe the bug**
When adding a device in Display Configurations the top two options are missing (App button only and Variable), or not able to scroll up

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Display configurations
2. Click on New Display Item, then drop down Device
3. See error

**Expected behaviour**
In former app versions there where three options, App button only, Variable and Custom MQTT, just as adding a device in the Button Configuration. In 2.16 the Button Configuration is still working as expected.

Display configuration selecting device:
![image](https://github.com/AdyRock/com.ady.button_plus/assets/10448491/503ae3fc-5d88-4f5c-8fd6-baef42a668f4)

Button configuration selecting device:
![image](https://github.com/AdyRock/com.ady.button_plus/assets/10448491/e79ba301-f276-4b1b-b46f-1acb0f7dc82d)

**Comment by Torch1969** [comment]
I cannot confirm this. For me the complete dropdown is shown (both on large display (iPad) and small display (iPhone)

**Comment by AdyRock** [comment]
I can see they are missing, although "App button only" doesn't apply to display items, so it is just the variable option that is not there
