### ISSUE TITLE
Buttom presses are sometimes mixed up

### ISSUE THREAD

**Issue by AAdam-Microfocus** [AdyRock/com.ady.button_plus#80]
**Homey**
- Model: 2023
- App Version: 0.2.30

**Describe the bug**

Button Presses are not correct. 
I pressed the 4 buttons on the right side from to to down and got the result as in the screenshot. Two is missing and Three is shown as left.
Each of the bars has one config assigned.

<img width="999" alt="grafik" src="https://github.com/AdyRock/com.ady.button_plus/assets/84076137/d60f827d-fc95-4303-8822-23522e6ab2fa">

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by AdyRock** [comment]
Can you try the test version of the app as I think that issue is now fixed.

**Comment by AAdam-Microfocus** [comment]
Thanks, looks good now.
<img width="1000" alt="grafik" src="https://github.com/AdyRock/com.ady.button_plus/assets/84076137/51b68313-e69d-4695-aa39-d6699485cac6">

**Comment by AAdam-Microfocus** [comment]
Hi, I just had again the problem with v.0.2.31. 
Buttom 3 RIGHT is tracked as Buttom 3 LEFT.
I did restart the app, re-assigned the configs and restarted the device. Same problem. I only did not restart the HP2023.

<img width="994" alt="grafik" src="https://github.com/AdyRock/com.ady.button_plus/assets/84076137/732ab605-0763-48b7-bad7-1139f4d6bd84">


MQTT shows right for the event ?
<img width="524" alt="grafik" src="https://github.com/AdyRock/com.ady.button_plus/assets/84076137/69ec7943-af4d-4fbf-a357-1bbcf759753d">

**Comment by AdyRock** [comment]
Do you have the same variable setup for both buttons?

**Comment by AAdam-Microfocus** [comment]
No, the left button is assigned to a virtual device, the right button to a variable

**Comment by AAdam-Microfocus** [comment]
I had to do a hardware reset to test my issue with the thermometer generating 1600 MQTT events per minute. I used your re-apply config menu which worked like a charme.
Unfortunately, the issue still exists, button 3 right does not work

**Comment by AAdam-Microfocus** [comment]
Hi, I tried the .33 version, still exist. The issue is only if I apply a variable. Applying App Button only shows correct 3R for 3 right.

**Comment by AdyRock** [comment]
I have hopefully found the problem and published a new version.
Thank you for your patience and narrowing down the scenario.

**Comment by AAdam-Microfocus** [comment]
No, problem still persist with v.3.4

**Comment by AAdam-Microfocus** [comment]
Hi, I can confirm this is fixed now with v. .35
