### ISSUE TITLE
Display buttons cannot be assigned to configuration

### ISSUE THREAD

**Issue by relshout85** [AdyRock/com.ady.button_plus#84]
**Homey**
- Model: 2023
- Firmware Version: 10.2.1
- App Version: 0.3.7

**Describe the bug**
Unable to assign buttons in the display.
I have 1 display and 2 bars installed (6 buttons in total).
But I am not able to assign configuration to the buttons that are part of the display. 

**To Reproduce**
Steps to reproduce the behaviour:

Path 1 via flow
1. Create a new flow.
2. Add a 'start' card (to start the flow) 
3. Add a 'then' card
4. Change connector **2** to button configuration **2** (Wissel connector 2 naar knop configuratie 2)
5. See error: Invalid Capability: configuration_button.connector1
(if I choose connector 1 this is the error 'Missing Capability Listener: configuration_button.connector0')

Note:
- I changed the same flow to connector 3 or 4 (which are by button bars), and those work.
- I create multiple button configurations 1/2/3 and all give the same issue.

Path 2 via button+ device configuration
1. Open button+ device from devices
2. Go to configuration tab (3rd option on bottom)
3. Only 3 options available
- Display connector 2
- Button connector 3
- Button connector 4
I would expect to have 3 options to assign buttons as I have display buttons and 2 additional bars (4 connectors in total?)

**Expected behaviour**
If I assign a button configuration to the display buttons I expect that to not fail, but to assign button actions to those buttons (maybe not the labels or top labels since, not sure how that would work with display configuration).
Main issue is that the buttons are useless as they cannot contain any action.

**Screenshots**

**Additional context**

**Comment by AdyRock** [comment]
At the moment the display buttons are so different that the button configuration is not compatible. So, they can only trigger Flows when pressing them and the Flow can perform the required actions.
