### ISSUE TITLE
Internal temperature value not updating when used on display

### ISSUE THREAD

**Issue by GithubBram** [AdyRock/com.ady.button_plus#85]
**Homey**
- Model: 2019
- Firmware Version: 10.0.5
- App Version: v0.3.7

**Describe the bug**
When using the internal temperature as "function" in a display config item, (measure_temperature}) is not updating

**To Reproduce**
Steps to reproduce the behaviour:
Add (measure_temperature}) as function in a display item.

**Expected behaviour**
The (internal) temperature value is updating on the display, like the internal time, internal date, or external tags.

**Screenshots**
![Button_plus_temp](https://github.com/AdyRock/com.ady.button_plus/assets/45642947/daa8b80e-7b5e-4bda-b2e7-4a949122a828)
![Button_plus_temp_Homey](https://github.com/AdyRock/com.ady.button_plus/assets/45642947/16994d1b-2f13-4e71-b6ca-90f96e64395a)
![Button_plus_temp_Insights](https://github.com/AdyRock/com.ady.button_plus/assets/45642947/5a4a2875-89d2-4edb-b003-395c7b0fb68f)

**Additional context**

**Comment by AdyRock** [comment]
New test version in the store

**Comment by GithubBram** [comment]
Hello Adrian,
It's working perfectly now, thanks!
Kind regards,
Bram
