### ISSUE TITLE
No longer able to install the app on homey Pro (early 2023)

### ISSUE THREAD

**Issue by r2-4u** [AdyRock/com.ady.button_plus#86]
**Homey pro**
- Model: 2023
- Firmware Version:  10.2.1
- App Version:  0.3.7

I tried to use the Button+ app after installing it last week. However the button+ app didn't work (brightness control doesn't work, buttons don't work, changes not working) only the update firmware options worked.
I tried to uninstall the app on the homey pro, but the now it can't install anymore (not compatible with the selected homey)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to homey store
2. Search for the button+ app
3. Press install
4. See the currently selected homey pro no longer available and get 2 warnings
![Screenshot_20240121-001433](https://github.com/AdyRock/com.ady.button_plus/assets/48524527/2c5e6217-c8e3-4793-88dc-aa9aa3fdf94a)

I tried to do a factory reset on the honey pro, but to no avail.

**Expected behaviour**
Be able to install the app on my homey pro early 2023 just like last week!

**Comment by AdyRock** [comment]
In the image there is no Homey selected in the drop list, so I guess it doesn't know where to install it. Unfortunately, I have no control over the store so you will need to contact Athom about that.

**Comment by r2-4u** [comment]
It seems there is a mixup between two accounts.
I am logged in to account A, and when I install the app, it is logged in to account B.
So, you are right, it is a problem at Homey.
I thought it might have been a manifest problem due to updates or so, but it was not.
Sorry to have bothered you with this!


________________________________

**Comment by AdyRock** [comment]
No problem. Always happy to try and help if I can.
