### ISSUE TITLE
Extra curly bracket in capability names in Display and Button configurations

### ISSUE THREAD

**Issue by oh2th** [AdyRock/com.ady.button_plus#88]
**Homey**
- Model: [2023]
- Firmware Version: 10.2.1
- App Version: my.homey.app web

**Describe the bug**
When creating Display Configurations or Button Configurations from App settings, there are extra curly backet `}` in capability names.

**To Reproduce**
Steps to reproduce the behaviour:
- Enter App settings
- Go to Display/Button Configuration
- Select device
- Open capability list

**Expected behaviour**

**Screenshots**
<img width="455" alt="Screenshot 2024-01-22 at 16 28 07" src="https://github.com/AdyRock/com.ady.button_plus/assets/59442255/20ed8e48-73ed-47be-a718-74ba1b1cecef">

**Additional context**

**Comment by AdyRock** [comment]
Thanks for the image as it makes it totally clear what the problem is. 
I will try to fix it in the next update.
