### ISSUE TITLE
Adjust display/button brightness

### ISSUE THREAD

**Issue by denniedegroot** [AdyRock/com.ady.button_plus#91]
I would like to adjust the display/button brightness with flow cards.
A use case for this is to dim the screen/buttons to 0% at night or when nobody is in the room where the Button+ is.

Ps: this would also extend the display lifetime.

**Comment by AdyRock** [comment]
At the moment, the brightness is only available via the configuration and I have submitted pull requests to make it available via MQTT, but I'm still waiting for that.

**Comment by AdyRock** [comment]
OK, after speaking with Ronald, it seems unlikely that the pull request to control the brightness via MQTT will be accepted. That slo means there is no way to control the LED brightness, which I also added.
So, I have added the Flow action card to changed the Large and Mini display brightness via the config API.

**Comment by denniedegroot** [comment]
You work fast! It works like a charm, thanks!
