### ISSUE TITLE
Status bar is shown after restart, even if status set to off in settings.

### ISSUE THREAD

**Issue by Torch1969** [AdyRock/com.ady.button_plus#94]
**Homey**
- Model: 2019
- Firmware Version: 1.08
- App Version: 0.3.15

**Describe the bug**
[A clear and concise description of what the bug is.](https://community.homey.app/t/button-release-0-3-7-test-0-3-15/89931/284?u=torch1969)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
After restart the status is still of if selected in settings.

**Screenshots**

**Additional context**
Maybe resend the statusbar setting when reconfigure settings to button+ device

**Comment by Torch1969** [comment]
It think that, thanks to the firmware 1.081 update where the problem with large configurations was solved, this bug doesn’t show himself anymore. So maybe it is solved that way….

**Comment by Ranney1** [comment]
Here the same. Had this issue. Since the latest firmware update it stays at the setting. Even after a reboot/Power cut.
