### ISSUE TITLE
THEN Cards for changing button text have no effect 

### ISSUE THREAD

**Issue by jnk-cons** [AdyRock/com.ady.button_plus#95]
**Homey**
- Model: 2023
- Firmware Version: 10.2.1
- App Version: 0.3.15

**Describe the bug**
If you use the THEN cards to set the button texts, the card is run through successfully, but the text does not change. The on/off texts do not seem to be taken into account either

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a FLow and add a THEN card to configure a Left/Rights button Label (top label or label, nothing works)
2. Click on Flow start or test the card
3. Button Text does not change

**Expected behaviour**
The text of the button should change

**Screenshots**

**Additional context**

**Comment by AdyRock** [comment]
I can't reproduce this, so could you provide some more details of how you have configured the button.

I have setup my flow:
![image](https://github.com/AdyRock/com.ady.button_plus/assets/38184396/ab1bb0fa-6fab-400d-a7d9-06b89eb8cd6d)
And when I run it the text on the button changes.
If I connect a capability to the button, the on and off text changes when the capability switches (which also replaces the text iIsent from the Flow).

**Comment by jnk-cons** [comment]
Hm ... my fault. After it simply wouldn't work, I just restarted the device (without success). After restarting the Homey app, it works as usual. Sry for the issue ...

Keep working on the product. It's already good and has real potential!
