### ISSUE TITLE
Button labels do not change

### ISSUE THREAD

**Issue by GithubBram** [AdyRock/com.ady.button_plus#98]
**Homey**
- Model: Pro 2023
- Homey Firmware Version: 10.3.0
- App Version: 0.4.0
- Button+ Firmware Version: 1.1

**Describe the bug**
Button labels (top and main) do not change when the button bar configuration is changed. But the functionality (capability, i.e. the assigned device) of the buttons do change correctly.

**To Reproduce**
Steps to reproduce the behaviour:
Choose bar config
Change bar config by Homey action card

**Expected behaviour**
Button labels do not change

**Screenshots**

**Additional context**

**Comment by AdyRock** [comment]
I can't reproduce this one. Could you enable the logging in the app settings, change the configuration and then send the log.

**Comment by AdyRock** [comment]
Ah, just reset my Button + and now I see the same problem, so I am looking into it.

**Comment by denniedegroot** [comment]
For me the buttons next to labels also do not work. The display does update it’s values. @AdyRock do you have some inside knowledge if this is app or firmware related?

**Comment by AdyRock** [comment]
@denniedegroot is this working OK in the new test versions?

**Comment by denniedegroot** [comment]
@AdyRock yes it is working again. Thank you for your support!
