### ISSUE TITLE
Display action card not registered

### ISSUE THREAD

**Issue by GithubBram** [AdyRock/com.ady.button_plus#99]
**Homey**
- Model: Pro 2023
- Homey Firmware Version: 10.3.0
- App Version: 0.4.0
- Button+ Firmware Version: 1.1

**Describe the bug**
When I make a flow to select the first page of the display (at least, I think this is it) it gives an error "card not registered", see attachment

**To Reproduce**
Steps to reproduce the behaviour:
1. Create two pages in display 1
2. Set to page 2 with display button
3. Create flow to change display to first page
4. Run the flow

**Expected behaviour**
First page of display is shown on Button+ device

**Screenshots**
See attachment
![Display_card_not_registered](https://github.com/AdyRock/com.ady.button_plus/assets/45642947/a735316d-f295-4a8a-baca-9f738fd4d1fa)

**Additional context**
Diag report ID
852d0371-d671-4133-a2cf-96f2485c17ef

**Comment by AdyRock** [comment]
Thanks for reporting it. It will be fixed in the next update.
